### ISSUE TITLE
Practica 3 mockup

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-proo#2]
[Practica_Mockup.docx.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-proo/files/8452559/Practica_Mockup.docx.pdf)

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/163228815-8f2f9c31-b41d-4cf0-84d9-ba1f673808fe.png)
Para poder iniciar sesion en una Dapp utilizando el protocolo Near..no es necesario registrar al usuario..

**Comment by josealfredo79** [comment]
Aqui dejo un ejemplo como se loguea a una Dapp en Near 

![image](https://user-images.githubusercontent.com/58342642/163231049-aba2e823-890d-424a-8c8b-888214ac122e.png)

https://learnnear.club/es/top-5-juegos-en-near/

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/163231164-535d10f4-d0b6-4df2-ac0a-f2b3bd51edc9.png)
La plataforma Web 3.0 no es necesario loguearlo con Google o Facebook.
Deben diseñar la app para una Dapp y entender el proceso de logueo en una Dapp con Near

**Comment by josealfredo79** [comment]
Favor de corregir por favo

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/163232034-41a5d5e1-4235-4956-b84a-f9911576af61.png)
Tener en cuenta que se conecta a la Wallet de mainnet de Near

**Comment by josealfredo79** [comment]
https://learnnear.club/near-protocol-ecosystem/chain-typing/
https://learnnear.club/es/top-5-juegos-en-near/ Aqui pueden checar unos ejemplos de logueo en Near 
![image](https://user-images.githubusercontent.com/58342642/163236444-452f8445-5338-458e-be50-5bf1f9933621.png)

**Comment by carlos-chrs** [comment]
Se uso la web 2.0

**Comment by josealfredo79** [comment]
Los talleres que se van a realizar son principalmente en tecnología Web
3.0, en próximas clases se va explicar como guardar informacion en los
contratos inteligentes, si se utiliza tecnología 3.0 no se podrán revisar
las próximas practicas, muchas gracias.

**Comment by carlos-chrs** [comment]
Se implemento la Tecnología web 2.0, fue la arquitectura que eligió el equipo desde un principio.
